### ISSUE TITLE
Error: getUserMedia is not implemented in this browser

### ISSUE THREAD

**Issue by j1980mac** [addpipe/simple-vmsg-demo#2]
Awesome plugin! 

Works great on Desktop everywhere. However it appears that there's an issue with "getUserMedia" not being supported on mobile (iOS) Chrome and FireFox. 
![Chrome](https://user-images.githubusercontent.com/51415039/58973937-ce6b0b80-8786-11e9-9307-036536982403.png)
![FireFox](https://user-images.githubusercontent.com/51415039/58974026-0f632000-8787-11e9-89a5-63ebef1c5d71.png)

Any possibility you'd be willing to fix that?

**Comment by octavn** [comment]
Firefox and Chrome on iOS do not support `getUserMedia()` only Safari does.

**Comment by j1980mac** [comment]
@octavn is it possible for this library to use a different function for FireFox and Chrome on iOS browsers?

**Comment by octavn** [comment]
You could but there's no other API to use to capture (only) the microphone. [Browsers on iOS devices do not support audio only recording through HTML Media Capture either](https://stackoverflow.com/a/43737156). Through HTML Media Capture they support only video + audio.

Chrome and Firefox on iOS have to use the same WebKit engine underneath as Safari. Only the UI/sync/services differ.

**Comment by j1980mac** [comment]
Even though they have the same WebKit engine, I can still record on Safari in iOS? 

Since Safari works, does this mean that the issue is in the FireFox and Chrome sync service then?
